# conda env create -f environment.yaml
# conda activate calc_biomass
name: calc_biomass
channels:
  - https://repo.prefix.dev/conda-forge
  - conda-forge
dependencies:
  - python=3.14
  - pandas
  - openpyxl
  - pint
  - pint-pandas
  # below for using th ./labs files
  - jupyterlab
  - matplotlib
  - nodejs
  - ipympl
